### ISSUE TITLE
How long does it take to train the model for segmentation?

### ISSUE THREAD

**Issue by Yiir-1** [fudan-zvg/PolarFormer#4]
Hello！Thanks for your good work ! Could you please explain what GPU you used to train models, and how long does it take?

**Comment by yanqinJiang** [comment]
Hi! We train the segmentation model on 8 A100 GPUs, and it takes about 20 and 25 hours to train PolarFormer and PolarFormer-T, respectively. (A100 GPU is not a must for the training of PolarFormer, we simply use it to accelerate training. You can just reduce the batch size and train it on 3090 or V100 GPUs.)

**Comment by Yiir-1** [comment]
Thanks for reply !
