### ISSUE TITLE
conversion of Polar coordinates and the Polar alignment module

### ISSUE THREAD

**Issue by lwq54013** [fudan-zvg/PolarFormer#6]
hi, thx for your great work, I have some questions when i read the code. Which part of the code reflects the conversion of Polar coordinates and the Polar alignment module in the paper. thx for your reply.

**Comment by yanqinJiang** [comment]
hi, thx for ur interest in our work. 
Please refer to [this](https://github.com/fudan-zvg/PolarFormer/blob/main/projects/mmdet3d_plugin/core/bbox/util.py) for the conversion of Polar coordinates, and refer to [this](https://github.com/fudan-zvg/PolarFormer/blob/main/projects/mmdet3d_plugin/models/necks/fpn_trans.py#L241) to see Polar alignment module in the paper. Feel free to ask more questions. : )

**Comment by lwq54013** [comment]
thx for your patient answer！
