### ISSUE TITLE
Train on 3090

### ISSUE THREAD

**Issue by iris0329** [fudan-zvg/PolarFormer#9]
Hi! Thanks for opening source this great work! 

I use the provided command to train the method on 3090, it will raise `RuntimeError: CUDA out of memory` error
```
tools/dist_train.sh projects/configs/polarformer/polarformer_r101.py 8 --work-dir work_dirs/polarformer_r101/
```
I didn't find how to change the batch size. Could you give me some ideas?

**Comment by WUMINGCHAzero** [comment]
Sorry, there is no batch_size option in config, you have to do some modifications to the code to change the batch_size. Currently, the r101 version of PolarFormer takes up about 29G GPU memory under the setting of batch_size = 1, so I'm afraid it cannot be trained on 3090. But you can change the backbone from r101 to r50/r34 in configs, and that will work on 3090. Do remember to modify [fpn_cfg: in_channels](https://github.com/fudan-zvg/PolarFormer/blob/main/projects/configs/polarformer/polarformer_r101.py#L59) according to the backbone you choose.

**Comment by yanqinJiang** [comment]
Sorry, there is no batch_size option in config, you have to do some modifications to the code to change the batch_size. Currently, the r101 version of PolarFormer takes up about 29G GPU memory under the setting of batch_size = 1, so I'm afraid it cannot be trained on 3090. But you can change the backbone from r101 to r50/r34 in configs, and that will work on 3090. Do remember to modify [fpn_cfg: in_channels](https://github.com/fudan-zvg/PolarFormer/blob/main/projects/configs/polarformer/polarformer_r101.py#L59) according to the backbone you choose.

**Comment by iris0329** [comment]
Ah, I see, I will try to use r50/r34 to have a test, many thanks!

**Comment by sinsin1998** [comment]
> Ah, I see, I will try to use r50/r34 to have a test, many thanks!

hello? Could you tell me how to modify the in_channel? I change it to 
<img width="456" alt="image" src="https://user-images.githubusercontent.com/82814185/232947858-a22274e7-b5f5-4a35-a0f4-959a654c0cef.png">
but got wrong

**Comment by iris0329** [comment]
@sinsin1998 Hi, if you only want to play this repo, an easier way is you can try to decrease the input image number, say the input of the original code uses 6 images per batch, and you can try to use 3 images.
